# Generated by Django 3.2.3 on 2021-05-31 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='when',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='download',
            name='file',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='download',
            name='user',
            field=models.CharField(editable=False, max_length=255),
        ),
    ]
